[debug] [2018-02-24T23:43:04.132Z] ----------------------------------------------------------------------
[debug] [2018-02-24T23:43:04.138Z] Command:       /usr/local/nvm/versions/node/v8.5.0/bin/node /usr/bin/firebase serve
[debug] [2018-02-24T23:43:04.138Z] CLI Version:   3.17.4
[debug] [2018-02-24T23:43:04.138Z] Platform:      linux
[debug] [2018-02-24T23:43:04.138Z] Node Version:  v8.5.0
[debug] [2018-02-24T23:43:04.138Z] Time:          Sat Feb 24 2018 17:43:04 GMT-0600 (CST)
[debug] [2018-02-24T23:43:04.138Z] ----------------------------------------------------------------------
[debug] 
[debug] [2018-02-24T23:43:04.149Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2018-02-24T23:43:04.149Z] > attempting to authenticate via app default credentials
[debug] [2018-02-24T23:43:04.187Z] ya29.GqUBbAVYPToqH4BzBVGl_avIOcWWM4dcPc_9beNKZyMTG2rG7ROuKsyb8Tq3XdHgiNf8jWjA_SVxXmDH_mzb3pTq8qRFQWJPv6VSj-pZx5KiTx6qpDs3Dp0XwQ3QlalSg3gpUMSyYqiYEilgOOwkwHSPFab28omBTZ7NKrg6H8WvXDTy5aMuYw_TPWqJsw4PcJzzceSNrOzUQmnTJx0Q1XfgA4rytTjQ
[debug] [2018-02-24T23:43:04.187Z] > retrieved access token via default credentials
[debug] [2018-02-24T23:43:04.189Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/oci-iot-ml  
  
 Sat Feb 24 2018 17:43:04 GMT-0600 (CST)
[debug] [2018-02-24T23:43:04.392Z] <<< HTTP RESPONSE 200
[debug] [2018-02-24T23:43:04.393Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/oci-iot-ml/tokens  
  
 Sat Feb 24 2018 17:43:04 GMT-0600 (CST)
[debug] [2018-02-24T23:43:04.596Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/home/marchd/piCam/weather'...
[info] 
[debug] [2018-02-24T23:43:04.599Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/oci-iot-ml  
  
 Sat Feb 24 2018 17:43:04 GMT-0600 (CST)
[debug] [2018-02-24T23:43:04.665Z] <<< HTTP RESPONSE 200
[debug] [2018-02-24T23:43:04.665Z] >>> HTTP REQUEST GET https://mobilesdk-pa.googleapis.com/v1/projects/32484548601/clients/_:getWebAppConfig  
  
 Sat Feb 24 2018 17:43:04 GMT-0600 (CST)
[debug] [2018-02-24T23:43:04.912Z] <<< HTTP RESPONSE 200
[debug] [2018-02-24T23:43:05.054Z] TypeError: Cannot read property 'public' of undefined
    at Server.<anonymous> (/usr/local/nvm/versions/node/v8.5.0/lib/node_modules/firebase-tools/lib/serve/hosting.js:34:17)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at Server.emit (events.js:207:7)
    at emitListeningNT (net.js:1370:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[error] 
[error] Error: An unexpected error has occurred.
